// scripts/upload-photos.ts — generate responsive variants and upload to GCS.
//
// Usage:
//   npx tsx scripts/upload-photos.ts <masters-dir>
//
// For each <slug>.jpg in <masters-dir>, emits 12 files to gs://deriva-photos/v1/:
//   <slug>-<w>.avif   (480, 960, 1440, 1920)
//   <slug>-<w>.webp   (same widths)
//   <slug>-<w>.jpg    (same widths)
//
// Each upload sets Cache-Control: public, max-age=300 (short TTL, no
// immutable), so overwrites propagate within ~5 minutes. Bump to a new
// prefix (v2, v3, …) only when you need guaranteed instant propagation.
//
// At the end writes src/data/photos.ts — a typed manifest the rest of the
// app reads to render <picture> / srcset. The bucket URL is never hardcoded
// in components; only this manifest knows about it.

import sharp from "sharp";
import { promises as fs } from "node:fs";
import { spawn } from "node:child_process";
import { tmpdir } from "node:os";
import path from "node:path";

const BUCKET = "deriva-photos";
const VERSION_PREFIX = "v2";
const CDN_HOST = "media.derivastudio.cl";
const WIDTHS = [480, 960, 1440, 1920] as const;
const FORMATS = [
  { ext: "avif", mime: "image/avif", quality: 55 },
  { ext: "webp", mime: "image/webp", quality: 75 },
  { ext: "jpg", mime: "image/jpeg", quality: 82 }
] as const;

type GeneratedFile = {
  slug: string;
  width: number;
  format: (typeof FORMATS)[number]["ext"];
  buffer: Buffer;
  contentType: string;
};

type ManifestEntry = {
  slug: string;
  /** Source aspect: width / height. */
  aspect: number;
  /** Available variant widths, ascending. */
  widths: number[];
};

async function generateVariants(
  masterPath: string,
  slug: string
): Promise<{ files: GeneratedFile[]; aspect: number }> {
  const master = sharp(masterPath, { failOn: "none" });
  const meta = await master.metadata();
  if (!meta.width || !meta.height) {
    throw new Error(`${slug}: cannot read dimensions`);
  }
  const aspect = meta.width / meta.height;
  const files: GeneratedFile[] = [];
  for (const targetWidth of WIDTHS) {
    // Don't upscale: clamp the variant to the source width.
    const w = Math.min(targetWidth, meta.width);
    const resized = sharp(masterPath, { failOn: "none" })
      .rotate() // honor EXIF orientation
      .resize({ width: w, withoutEnlargement: true });
    for (const fmt of FORMATS) {
      let pipeline = resized.clone();
      if (fmt.ext === "avif") pipeline = pipeline.avif({ quality: fmt.quality, effort: 6 });
      else if (fmt.ext === "webp") pipeline = pipeline.webp({ quality: fmt.quality, effort: 5 });
      else pipeline = pipeline.jpeg({ quality: fmt.quality, mozjpeg: true });
      const buffer = await pipeline.toBuffer();
      files.push({ slug, width: targetWidth, format: fmt.ext, buffer, contentType: fmt.mime });
    }
  }
  return { files, aspect };
}

function runGcloud(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn("gcloud", args, { stdio: ["ignore", "ignore", "pipe"] });
    let stderr = "";
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`gcloud exited ${code}: ${stderr.trim()}`));
    });
  });
}

async function upload(file: GeneratedFile): Promise<void> {
  const key = `${VERSION_PREFIX}/${file.slug}-${file.width}.${file.format}`;
  // Write to a temp file, then `gcloud storage cp` it. We set the
  // metadata flags directly on the cp call so the object lands with the
  // right Content-Type + Cache-Control on first upload.
  const tmp = path.join(tmpdir(), `deriva-upload-${process.pid}-${Date.now()}-${path.basename(key)}`);
  await fs.writeFile(tmp, file.buffer);
  try {
    await runGcloud([
      "storage",
      "cp",
      tmp,
      `gs://${BUCKET}/${key}`,
      `--content-type=${file.contentType}`,
      "--cache-control=public, max-age=300",
      "--quiet"
    ]);
  } finally {
    await fs.unlink(tmp).catch(() => undefined);
  }
  const kb = (file.buffer.length / 1024).toFixed(0);
  console.log(`  ✓ ${key.padEnd(40)} ${kb} KB`);
}

async function writeManifest(entries: ManifestEntry[]): Promise<void> {
  const sorted = [...entries].sort((a, b) => a.slug.localeCompare(b.slug));
  const lines = [
    "// Generated by scripts/upload-photos.ts — do not edit by hand.",
    "// Run `npm run photos:upload <masters-dir>` to regenerate.",
    "",
    "export const PHOTO_BASE_URL =",
    `  "https://${CDN_HOST}/${VERSION_PREFIX}";`,
    "",
    "export const PHOTO_WIDTHS = [480, 960, 1440, 1920] as const;",
    "",
    "export const PHOTO_FORMATS = [",
    '  { ext: "avif", mime: "image/avif" },',
    '  { ext: "webp", mime: "image/webp" },',
    '  { ext: "jpg",  mime: "image/jpeg" }',
    "] as const;",
    "",
    "export type PhotoSlug =",
    ...sorted.map((e, i) => `  | "${e.slug}"${i === sorted.length - 1 ? ";" : ""}`),
    "",
    "export type PhotoEntry = {",
    "  slug: PhotoSlug;",
    "  aspect: number;",
    "  widths: number[];",
    "};",
    "",
    "export const derivaPhotos: Record<PhotoSlug, PhotoEntry> = {",
    ...sorted.map(
      (e) =>
        `  "${e.slug}": { slug: "${e.slug}", aspect: ${e.aspect.toFixed(4)}, widths: [${e.widths.join(", ")}] },`
    ),
    "};",
    ""
  ];
  await fs.writeFile("src/data/photos.ts", lines.join("\n"));
  console.log("✓ wrote src/data/photos.ts");
}

async function writeLocal(file: GeneratedFile): Promise<void> {
  const key = `${VERSION_PREFIX}/${file.slug}-${file.width}.${file.format}`;
  const target = path.join("public/photos", key);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, file.buffer);
  const kb = (file.buffer.length / 1024).toFixed(0);
  console.log(`  ✓ public/photos/${key.padEnd(40)} ${kb} KB`);
}

async function main() {
  const args = process.argv.slice(2);
  const localOnly = args.includes("--local");
  const mastersDir = args.filter((a) => !a.startsWith("--"))[0];
  if (!mastersDir) {
    console.error("usage: tsx scripts/upload-photos.ts <masters-dir> [--local]");
    console.error("  default: generate variants and upload to GCS");
    console.error("  --local: skip GCS, write variants to public/photos/v1/ for dev parity");
    process.exit(1);
  }
  const absDir = path.resolve(mastersDir);
  const all = await fs.readdir(absDir);
  const masters = all
    .filter((f) => /\.(jpe?g|png)$/i.test(f))
    .filter((f) => !f.startsWith("."))
    .map((f) => ({ file: f, slug: path.basename(f).replace(/\.(jpe?g|png)$/i, "") }));
  if (masters.length === 0) {
    console.error(`no jpg/png masters found in ${absDir}`);
    process.exit(1);
  }
  console.log(`→ found ${masters.length} masters in ${absDir}`);
  const entries: ManifestEntry[] = [];
  for (const m of masters) {
    console.log(`\n[${m.slug}]`);
    const { files, aspect } = await generateVariants(path.join(absDir, m.file), m.slug);
    for (const f of files) {
      if (localOnly) await writeLocal(f);
      else await upload(f);
    }
    entries.push({ slug: m.slug, aspect, widths: [...WIDTHS] });
  }
  if (!localOnly) {
    // Only regenerate the manifest on real uploads — local-only is a dev mirror.
    await writeManifest(entries);
  }
  console.log(
    `\n✓ ${localOnly ? "wrote" : "uploaded"} ${entries.length} photos × ${WIDTHS.length} widths × ${FORMATS.length} formats`
  );
  console.log(`  ${localOnly ? "Local mirror: public/photos/" : `CDN base: https://${CDN_HOST}/`}${VERSION_PREFIX}/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
